name: .NET MVC CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on:
      - self-hosted
      - Linux
      - X64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Upload Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: publish
          path: publish/

  deploy:

    needs: build

    runs-on:
      - self-hosted
      - Linux
      - X64

    environment:
      name: production

    steps:

      - name: Download Publish Artifact
        uses: actions/download-artifact@v4
        with:
          name: publish
          path: publish

      - name: Create Incoming Directory
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "mkdir -p /home/user/apps/helloProject/incoming"

      - name: Copy Publish Files
        run: |
          scp -r publish/* \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/user/apps/helloProject/incoming/

      - name: Blue-Green Deployment
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} \
          "/home/user/apps/helloProject/deploy.sh"