name: .NET MVC CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on:
        - self-hosted
        - Linux
        - X64

    steps:
    - uses: actions/checkout@v4

    

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o publish

    - name: Deploy
      run: |
        rm -rf ~/apps/helloProject/publish/*
        cp -r publish/* ~/apps/helloProject/publish/

    - name: Restart Service
      run: sudo systemctl restart helloapp